site_name: Ham Pi
site_url: https://njsmithfm.github.io/ham-pi
theme:
  name: material
  font:
    text: Lato
    code: Roboto Mono
  palette:
    scheme: slate
    primary: purple
    accent: green

  icon:
    logo: fontawesome/brands/raspberry-pi
